

# This file was *autogenerated* from the file zh.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_10 = Integer(10); _sage_const_12 = Integer(12); _sage_const_6 = Integer(6); _sage_const_100 = Integer(100)
def linear_congruence_solutions(a, b, m, low, high):
    if low > high:
        raise ValueError()
    
    if b % gcd(a, m) != _sage_const_0 :
        raise ValueError()
    

    x = b / a

    if low < x < high:
        return x

print(linear_congruence_solutions(_sage_const_10 , _sage_const_12 , _sage_const_6 , _sage_const_10 , _sage_const_100 ))

